books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path('' , views.bookies , name='bookies'),
    path('books_detail/<int:pk>/' , views.books_detail , name='books_detail'),
    path('dataview/' , views.DataView.as_view() , name='DataView'),
]

project/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls' , namespace='users')),
    path('books/', include('books.urls' , namespace='books')),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/' , views.signup, name='signup'),
    path('login/' , views.user_login, name='login'),
    path('logout/' , views.logout, name='logout')
]

books/models.py
from django.db import models
from django.contrib.auth.models import User




class Books(models.Model):
    Category = (
    ('Statistic' , 'Statistic'),
    ('Mechanics' , 'Mechanics'),
    ('Networks' , 'Networks'),
    ('Electronics' , 'Electronics'),
    ('Machine Learning' , 'Machine Learning'),
    ('Biology' , 'Biology'),
    ('Physics' , 'Physics'),
    ('Computer Science' , 'Computer Science'),
    ('Big Data' , 'Big Data'),
)

    Title = models.CharField( max_length=50) 
    Category = models.CharField(choices=Category , default='Statistic' ,max_length=50)
    Views = models.IntegerField(default=0)
    ISBN = models.CharField( max_length=50) 
    Author = models.CharField(max_length=50)
    Yop = models.CharField( max_length=50)
    Publisher = models.CharField(max_length=50)
    

    class Meta:
        verbose_name = ("Book")
        verbose_name_plural = ("Bookies")

    def __str__(self):
        return self.Title
    
    def get_avg_rating(self):
        all_reviews = self.book_rate.all()
        all_rating = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_rating += review.rate
            return round(all_rating/len(all_reviews),2)
        else:
            return '0.0'

    def book_check(self):
        if self.book_rate > 0:
            return None



class Ratings(models.Model):
    Rating_Choises =(
    (1.0 , '1.0'),
    (2.0 , '2.0'),
    (3.0 , '3.0'),
    (4.0 , '4.0'),
    (5.0 , '5.0'),
    )
    user = models.ForeignKey(User,  on_delete=models.CASCADE)
    books = models.ForeignKey(Books , related_name='book_rate', on_delete=models.CASCADE)
    rate = models.FloatField(choices=Rating_Choises,default=0.0)

    class Meta:
        verbose_name = ("Rating")
        verbose_name_plural = ("Ratings")

    def __str__(self):
        return str(self.user.username)

users/models.py
from django.db import models

# Create your models here.

books/forms.py
import io
from django import forms
from .models import Books , Ratings
import csv

class DataForm(forms.Form):
    data_file = forms.FileField()

    def process_data(self):
        f = io.TextIOWrapper(self.cleaned_data['data_file'].file)
        reader = csv.DictReader(f)

        for books in reader :
            Books.objects.create(Title = books['title'], ISBN=books['ISBN'], Author=books['author'], Yop=books['yop'], Publisher=books['publisher'])

class RatingForm(forms.ModelForm):
    class Meta:
        model = Ratings
        fields = ('rate',)

users/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username' , 'password')

books/views.py
from django.shortcuts import render ,redirect
import pandas as pd
import csv
from .forms import DataForm ,RatingForm
from django.views.generic import FormView
from django.contrib.auth.models import User
import time
from .models import Books , Ratings



class DataView(FormView):
    template_name = 'csvbookform.html'
    form_class = DataForm

    def form_valid(self, form):
        form.process_data()
        return super().form_valid(form)


def bookies(request):
    book_list = Books.objects.all()
    return render(request, 'book_list.html' , {
        'book_list' : book_list , 
    })

def books_detail(request , pk):
    books_detail = Books.objects.get(pk=pk)
    cate = books_detail.Category
    print(cate)

    book_list = Books.objects.filter(Category=cate).order_by('?')[:5]

    books_detail.Views = books_detail.Views + 1
    books_detail.save()

    rating_detail = Ratings.objects.filter(books =books_detail ,user=request.user)

    if request.method == "POST":
        form = RatingForm(request.POST)
        if form.is_valid():
            if Ratings.objects.filter(books =books_detail ,user=request.user).exists():
                form = RatingForm()
            else:
                book_form = form.save(commit=False)
                book_form.user = request.user
                book_form.books = books_detail
                book_form.save()
                
            return redirect('books:bookies')
    else:
        form = RatingForm()

    return render(request, 'book_detail.html' , {
        'books_detail' : books_detail , 
        'form' : form , 
        'rating_detail' : rating_detail ,
        'book_list' : book_list , 
    })

users/views.py
from django.shortcuts import render ,redirect
from .forms import LoginForm
from django.contrib.auth import authenticate , login
from django.contrib import auth

def signup(request):
    
    return render(request, 'users/signup.html', {})



def user_login(request):
    if request.method == "POST":
        form = LoginForm()
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request , username=username , password=password)
        if user is not None :
            login(request , user)
            
    else:
        form = LoginForm()

    return render(request, 'users/user_login.html', {})


def logout(request):
    auth.logout(request)
    return redirect('users:login')

books/templates/book_detail.html
{% load static from staticfiles %}
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'books:bookies' %}">Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'users:signup' %}">SignUp</a>
            </li>


        </ul>
        <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        </div>
    </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-lg-4 mt-3 p-5 ">
                <div class="card" style="width: 18rem;border: double;height: 26rem;">
                    <div class="card-body">
                    <h5 class="card-title">{{books_detail.Title}}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Author : {{books_detail.Author}}</h6>
                    <p class="card-text">ISBN : {{books_detail.ISBN}}</p>
                    <p class="card-text">Publisher : {{books_detail.Publisher}}</p>
                    <p class="card-text">Date : {{books_detail.Yop}}</p>
                    <p class="card-text">Views : {{books_detail.Views}}</p>
                    
                    {% for rate in rating_detail %}
                    <p class="card-text">Your Ratings : {{rate.rate|floatformat:1}}</p>
                    {% endfor %}
                            

                                                    
                    
                    <div class="row" >
                        <form method="POST">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <button  class="btn btn-primary" type="submit">Save</button>
                        </form> 
                    </div>


                </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <h1>Recommendation Books</h1>
                {% for book in book_list %}
                <div class="col-lg-4 mt-3 p-5 ">
                    <div class="card" style="width: 18rem;border: double;height: 24rem;">
                        <div class="card-body">
                        <h5 class="card-title">{{book.Title}}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Author : {{book.Author}}</h6>
                        <p class="card-text">ISBN : {{book.ISBN}}</p>
                        <p class="card-text">Publisher : {{book.Publisher}}</p>
                        <p class="card-text">Date : {{book.Yop}}</p>
                        <p class="card-text">Views : {{book.Views}}</p>
                        <p class="card-text">Rate : {{book.get_avg_rating}}</p>
    
                        <a href="{% url 'books:books_detail' book.pk %}" class="card-link">Book Detail</a>
                        <div>
                            
                            
                            {% if book.get_avg_rating <= 1.0 %}
                            <span class="fa fa-star " style="color: orange;"></span>
                            {% elif book.get_avg_rating <= 2.0 %}
                            <span class="fa fa-star " style="color: orange;"></span>
                            <span class="fa fa-star " style="color: orange;"></span>
                            {% elif book.get_avg_rating <= 3.0 %}
                            <span class="fa fa-star " style="color: orange;"></span>
                            <span class="fa fa-star " style="color: orange;"></span>
                            <span class="fa fa-star " style="color: orange;"></span>
                            {% elif book.get_avg_rating <= 4.0 %}
                            <span class="fa fa-star " style="color: orange;"></span>
                            <span class="fa fa-star " style="color: orange;"></span>
                            <span class="fa fa-star " style="color: orange;"></span>
                            <span class="fa fa-star " style="color: orange;"></span>
                            {% elif book.get_avg_rating <= 5.0 %}
                            <span class="fa fa-star " style="color: orange;"></span>
                            <span class="fa fa-star " style="color: orange;"></span>
                            <span class="fa fa-star " style="color: orange;"></span>
                            <span class="fa fa-star " style="color: orange;"></span>
                            {% elif book.get_avg_rating >= 4.0 %}
                            <span class="fa fa-star " style="color: orange;"></span>
                            <span class="fa fa-star " style="color: orange;"></span>
                            <span class="fa fa-star " style="color: orange;"></span>
                            <span class="fa fa-star " style="color: orange;"></span>
                            <span class="fa fa-star " style="color: orange;"></span>
                            {% else %}
                            <h6>No Rate</h6>
                            {% endif %}
                    </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
    </div>

</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

books/templates/book_list.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'books:bookies' %}">Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'users:signup' %}">SignUp</a>
            </li>


        </ul>
        <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        </div>
    </div>
    </nav>
    <div class="container">
        <div class="row">
            {% for book in book_list %}
            <div class="col-lg-4 mt-3 p-5 ">
                <div class="card" style="width: 18rem;border: double;height: 24rem;">
                    <div class="card-body">
                    <h5 class="card-title">{{book.Title}}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Author : {{book.Author}}</h6>
                    <p class="card-text">ISBN : {{book.ISBN}}</p>
                    <p class="card-text">Publisher : {{book.Publisher}}</p>
                    <p class="card-text">Date : {{book.Yop}}</p>
                    <p class="card-text">Views : {{book.Views}}</p>
                    <p class="card-text">Rate : {{book.get_avg_rating}}</p>

                    <a href="{% url 'books:books_detail' book.pk %}" class="card-link">Book Detail</a>
                    <div>
                        
                        
                        {% if book.get_avg_rating <= 1.0 %}
                        <span class="fa fa-star " style="color: orange;"></span>
                        {% elif book.get_avg_rating <= 2.0 %}
                        <span class="fa fa-star " style="color: orange;"></span>
                        <span class="fa fa-star " style="color: orange;"></span>
                        {% elif book.get_avg_rating <= 3.0 %}
                        <span class="fa fa-star " style="color: orange;"></span>
                        <span class="fa fa-star " style="color: orange;"></span>
                        <span class="fa fa-star " style="color: orange;"></span>
                        {% elif book.get_avg_rating <= 4.0 %}
                        <span class="fa fa-star " style="color: orange;"></span>
                        <span class="fa fa-star " style="color: orange;"></span>
                        <span class="fa fa-star " style="color: orange;"></span>
                        <span class="fa fa-star " style="color: orange;"></span>
                        {% elif book.get_avg_rating <= 5.0 %}
                        <span class="fa fa-star " style="color: orange;"></span>
                        <span class="fa fa-star " style="color: orange;"></span>
                        <span class="fa fa-star " style="color: orange;"></span>
                        <span class="fa fa-star " style="color: orange;"></span>
                        {% elif book.get_avg_rating >= 4.0 %}
                        <span class="fa fa-star " style="color: orange;"></span>
                        <span class="fa fa-star " style="color: orange;"></span>
                        <span class="fa fa-star " style="color: orange;"></span>
                        <span class="fa fa-star " style="color: orange;"></span>
                        <span class="fa fa-star " style="color: orange;"></span>
                        {% else %}
                        <h6>No Rate</h6>
                        {% endif %}
                </div>
                    </div>
                </div>
            </div>
            {% endfor %}
    </div>
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

books/templates/csvbookform.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item">
            <a class="nav-link" href="#">Login</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="#">SignUp</a>
            </li>


        </ul>
        <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        </div>
    </div>
    </nav>
    <div class="col-lg-6 mt-5 p-5 ">
        <form method="POST"  enctype="multipart/form-data">
            {% csrf_token %}
            <label >Enter Your File CSV</label>
            <br>
            {{form}}
            <button class="btn btn-primary" type="submit">save</button>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/signup.html
<h1>Welcome User</h1>

users/templates/users/user_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <!--  This file has been downloaded from bootdey.com    @bootdey on twitter -->
    <!--  All snippets are MIT license http://bootdey.com/license -->
    <title>profile with data and skills - Bootdey.com</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://netdna.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style type="text/css">

.border-md {
    border-width: 2px;
}

.btn-facebook {
    background: #405D9D;
    border: none;
}

.btn-facebook:hover, .btn-facebook:focus {
    background: #314879;
}

.btn-twitter {
    background: #42AEEC;
    border: none;
}

.btn-twitter:hover, .btn-twitter:focus {
    background: #1799e4;
}


body {
    min-height: 100vh;
}

.form-control:not(select) {
    padding: 1.5rem 0.5rem;
}

select.form-control {
    height: 52px;
    padding-left: 0.5rem;
}

.form-control::placeholder {
    color: #ccc;
    font-weight: bold;
    font-size: 0.9rem;
}
.form-control:focus {
    box-shadow: none;
}

    </style>
</head>
<body>
<!-- Navbar-->



<div class="container">
    <div class="row mt-4 align-items-center ">
        <!-- For Demo Purpose -->

        <!-- Registeration Form -->
        <div class="col-md-7 col-lg-6">
            <form method="POST">
                {% csrf_token %}
                <div class="row">
                    <!-- UserName -->
                    <div class="input-group col-lg-6 mb-4">
                        <div class="input-group-prepend">
                            <span class="input-group-text bg-white px-4 border-md border-right-0">
                                <i class="fa fa-user text-muted"></i>
                            </span>
                        </div>
                        <input id="username" type="text" name="username" placeholder="Username" class="form-control bg-white border-left-0 border-md">
                    </div>


                    <!-- Password -->
                    <div class="input-group col-lg-6 mb-4">
                        <div class="input-group-prepend">
                            <span class="input-group-text bg-white px-4 border-md border-right-0">
                                <i class="fa fa-lock" aria-hidden="true"></i>
                            </span>
                        </div>
                        <input id="password" type="password" name="password" placeholder="Password" class="form-control bg-white border-left-0 border-md">
                    </div>


                    <!-- Submit Button -->
                    <div class="form-group col-lg-12 mx-auto mb-0">
                        <a href="#" class="btn btn-primary btn-block py-2">
                            <input id="form-button" class="btn btn-primary btn-block" type="submit" value="Login">
                        </a>
                    </div>

                    <!-- Divider Text -->
                    <div class="form-group col-lg-12 mx-auto d-flex align-items-center my-4">
                        <div class="border-bottom w-100 ml-5"></div>
                        <span class="px-2 small text-muted font-weight-bold text-muted">OR</span>
                        <div class="border-bottom w-100 mr-5"></div>
                    </div>



                    <!-- Already Registered -->
                    <div class="text-center w-100">
                        <p class="text-muted font-weight-bold">Create Account ? <a href=" class="text-primary ml-2">Signup</a></p>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>

<script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script type="text/javascript">
	
</script>
</body>
</html>